### ISSUE TITLE
Cannot find IonicNativeFcm

### ISSUE THREAD

**Issue by posdevelopers** [iAbhinav/ionic-native-fcm#1]
I am having the error cannot find IonicNativeFcm

**Comment by posdevelopers** [comment]
what i am going to import ?

**Comment by iAbhinav** [comment]
You may directly import the class in your service. No need to import in module.ts file.

```
import { IonicNativeFcm } from "ionic-native-fcm";
```

**Comment by tnssuet021** [comment]
Does this plugin compatible to work on apple store? Does this plugin contain uiwebview or wkwebview?

**Comment by iAbhinav** [comment]
Yes this is compatible with App Store norms. And does not contain any of
the above.

**Comment by tnssuet021** [comment]
Let me try this

**Comment by tnssuet021** [comment]
Hi
